### ISSUE TITLE
Run constraints without running tests

### ISSUE THREAD

**Issue by pug-pelle-p** [Snowflake-Labs/dbt_constraints#10]
Hi! We have a scheduled job every hour where we run DBT but we don't want to run the tests every hour, is it possible to run dbt constraints without running the tests? If so, how would I do that?

**Comment by danflippo** [comment]
It was a deliberate design choice to create constraints only when you actually know the test has passed. Is your use case on Snowflake or PostgreSQL? On Snowflake, I am inclined to say you should have to run the test but on PostgreSQL, we create DB enforced constraints so you would get a failed run if you created an invalid constraint. Can you also give more details on why you don't want to run the tests? I don't typically see tests taking up much time in my customers' projects due to the multi-threaded nature of dbt and Snowflake.

**Comment by danflippo** [comment]
Closing since no one has chimed in.

**Comment by brettwatkins-Built** [comment]
Hey @sfc-gh-dflippo, if you are forced to execute `dbt run` and then `dbt test` to add the keys, the tables created during the run are without a primary key for as long as the testing process takes to run. If they're a lot tests, this just doesn't scale.
