### ISSUE TITLE
Redshift Support

### ISSUE THREAD

**Issue by ataft** [Snowflake-Labs/dbt_constraints#25]
I'm trying to use `dbt_constraints.primary_key` with `not_null`, but get an "can not make a nullable column a primary key" error when trying to create the primary key. As I understand, dbt columns are always "nullable". Does the macro have to alter the column to be NOT NULL, or is there another way around this?

My test is defined as:
```
tests:
  - dbt_constraints.primary_key
  - not_null
```

**Comment by sfc-gh-dflippo** [comment]
Which database are you using with dbt constraints? I've never seen this error on Snowflake so I assume PostgreSQL or Oracle? I am actually about to add a contributed feature for not null constraints and I can take advantage of that to make columns not null before creating the PK constraint.

**Comment by ataft** [comment]
Yes, PostgreSQL. I thought this was standard for PK creation though.

**Comment by sfc-gh-dflippo** [comment]
Yes, I am surprised to see this because I know I've been testing PK constraints in my PostgreSQL integration tests. Nevertheless, I was going to automatically add a not null constraint for PK columns and I can just do that prior to the PK.

**Comment by ataft** [comment]
Apologies, I'm using the postgres constrains on Redshift. I thought they were the same, but I just tested on both PG and Redshift, and PG will only throw an error if there are NULL values in the column. It does not require the column to be NOT NULL. Redshift appears to require the column to be NOT NULL.

**Comment by sfc-gh-dflippo** [comment]
dbt Constraints only officially supports Snowflake, Oracle, and Postgres adapters because those are the DB I have access to at the moment. I'm surprised you were able to use the package at all with Redshift since I would have assumed that the adapter prefix for macros would need to be "redshift__", not "postgres__". Nevertheless, I am almost done testing the next version of the Snowflake/PostgreSQL/Oracle macros with the not null constraint support. I don't have my own Redshift environment to test with so I can't say if this will fix your issue or make it worse. For PostgreSQL, it will issue the following for all the columns in the PK:
```sql
ALTER TABLE <TABLE_NAME> ALTER COLUMN <COLUMN_NAME> SET NOT NULL, ALTER COLUMN <COLUMN_NAME2> SET NOT NULL;
```
This is executed before it tries to create the PK. If Redshift does not allow you to issue the above SQL to change a column to not null, this is probably going to make things worse.

Ideally, there should be a different redshift__create_constraints.sql file for Redshift with any differences necessary for Redshift. I would welcome someone else contributing such code but I don't plan to add it myself short-term. I do work for Snowflake, after all. :)

**Comment by ataft** [comment]
I copied your postgres adapter, renamed everything to "redshift", and changed the PK/FK lookups to check "information_schema" since the postgres SQL doesn't work with redshift. Everything else appears to work fine except the PK creation. Unfortunately, Redshift does not allow altering a column after it is created. I tried the following hack, which adds a new column, updates with data, drops the old, then renames:

```
{%- for column_name in column_names -%}
    {%- set alter_statement -%}
    ALTER TABLE {{table_relation}} ADD COLUMN {{column_name}}_tmp VARCHAR NOT NULL DEFAULT '';
    UPDATE {{table_relation}} SET {{column_name}}_tmp = {{column_name}};
    ALTER TABLE {{table_relation}} DROP COLUMN {{column_name}};
    ALTER TABLE {{table_relation}} RENAME {{column_name}}_tmp TO {{column_name}};
    {%- endset -%}
    {%- do log("Setting column " ~ column_name ~ " to NOT NULL in table " ~ table_relation, info=false) -%}
    {%- do run_query(alter_statement) -%}
{% endfor %}
```

However, you can't drop a column that's being used as a DISTKEY, so this doesn't really work well since your PK's will often be DISTKEY's. The only alternative I see is a full table creation and swap, but I'm not sure how hacky I want to get with this. If I get it working, I'll contribute the code back to this repo.

**Comment by sfc-gh-dflippo** [comment]
First, you should grab that code again because I just merged the branch for not null constraints. 

I suggest we just create unique keys for redshift. We can leave the PK test SQL alone so it will still verify not null and uniqueness. Then, by creating a UK, we can still support FK pointing to what would normally be a PK. I assume Redshift allows FK to a UK? (most DB do).

For the new not null constraints, in your redshift__create_not_null macros, I would just leave it empty. The logic in create_constraints will still call your macro but it wouldn't do anything. I have similar stuff in the Oracle macros since Oracle makes it hard to check privileges before executing statements.

**Comment by sfc-gh-dflippo** [comment]
@ataft , I have released v.0.5.0 with the not null constraints so I suggest you base your PR on that. Thanks in advance for your contribution.
