### ISSUE TITLE
Do not create constraints if error_if / warn_if is != 0

### ISSUE THREAD

**Issue by aa-matthias** [Snowflake-Labs/dbt_constraints#32]
Creation of constraints should be skipped if tests pass but do have a warn_if / error_if != 0 configured.

https://docs.getdbt.com/reference/resource-configs/severity

**Comment by sfc-gh-dflippo** [comment]
This behavior was by design. Can you explain the use care for why you wouldn't want constraints if the test passed? Many of my customer's set their tasks to "warn" to avoid nightly failures but if the relationship/unique tests pass, they want the constraints created. I already have logic to exclude tests that are set to warn and the test failed. Are you on Snowflake or a different DB that enforces constraints?

**Comment by aa-matthias** [comment]
We are in Snowflake. Mh you might be right, even If Not enforced in SF i was thinking about giving the wrong hints and assumptions, but a Join would give a false result anyhow If the data is e.g. non-unique.

**Comment by sfc-gh-dflippo** [comment]
Since we only create a constraint when a test passes, and we prohibit adding a `config: where:` parameter, the only constraints we create on any platform (Oracle and PostgreSQL enforce constraints) are ones we expect to be successfully. Snowflake never enforces constraints but [having an invalid FK can cause query results to change due to Join Elimination](https://docs.snowflake.com/en/user-guide/join-elimination.html). One of the reasons I created dbt Constraints is because I knew that Snowflake was about to release Join Elimination.
