### ISSUE TITLE
Optional foreign keys?

### ISSUE THREAD

**Issue by DwaneHall** [Snowflake-Labs/dbt_constraints#36]
Hey @sfc-gh-dflippo a really useful library you've created here thanks for all the hard work! This is not an issue just a question regarding your thoughts on including optional foreign key mappings?  Although not ideal there are circumstances where a user may run into a legacy data mapping that involves 0-1 or 0-* relationship between a child and parent.  In these circumstances the child foreign key can be NULL if there is no parent relationship.  The foreign key tests for this scenario appear to perform a check for null's between the relationship between the child (foreign) and parent (primary) mapping.  Under these circumstances the tests fail and the relationship is not created (as expected).  

```
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
with child as (
  select
    CHILD_ID
  from MY_SNOWFLAKE_SCHEMA.My_Child_Table
  where 1=1
        and CHILD_ID is not null     
),

parent as (
    select
        PARENT_ID
    from MY_SNOWFLAKE_SCHEMA.My_Parent_Table
),

validation_errors as (
    select
        child.*
    from child
    left join parent
        on parent.PARENT_ID = child.CHILD_ID
    where parent.PARENT_ID is null
)
select *
from validation_errors
      
    ) dbt_internal_test
```

Some Data Warehouses (like Snowflake) don't enforce these constraints (Except NULL) but for all the reasons mentioned in the README for enforcing the constraints (particularly reverse engineering Data Models) is there an opportunity to include an option to allow nulls on specific foreign key relationships? Any thoughts on the matter from your experience would be appreciated.

**Comment by sfc-gh-dflippo** [comment]
The way my foreign key logic is written, you *can* create FK on nulls. Yes, the SQL excludes any child rows from the FK test if there is a null but the effect is not that this prevents the relationship being created. You only fail a dbt test if your test results in rows and since the rows with nulls are excluded, they don't prevent the constraint from passing. I call out nulls in the readme because if you have a null in one column of a compound key, the other value is not checked against the parent because that is what the official SQL standard is. Essentially, if any of the columns in a FK are null then the row will pass the test.

```sql
with child as (
  select
    {{fk_columns_csv}}
  from {{model}}
  where 1=1
        {% for column in fk_columns_list -%}
        and {{column}} is not null
        {% endfor %}
),

parent as (
    select
        {{pk_columns_csv}}
    from {{pk_table_name}}
),

validation_errors as (
    select
        child.*
    from child
    left join parent
        on {{join_conditions | join(' and ')}}

    where parent.{{pk_columns_list | first}} is null
)

select *
from validation_errors
```
