### ISSUE TITLE
Feature request: add constraints to seeds

### ISSUE THREAD

**Issue by sfc-gh-cwiese** [Snowflake-Labs/dbt_constraints#37]
As a developer, I would like dbt_constraints to add constraints for my tests on [seeds](https://docs.getdbt.com/docs/build/seeds), so that I can benefit from join elimination in queries on my seed tables.

**Comment by kenho811** [comment]
Hi,

I have a similar request.

```
  dbt_constraints_seeds_enabled: true
```

The above configuration does not seem to work.

**Comment by sfc-gh-dflippo** [comment]
@kenho811 , I am checking in the code now but it won't actually require a new parameter to enable. I have that parameter for sources because they are more likely to be created by an external process and we are more likely to not have privileges to modify sources. Because a seed is created from your own project, I can assume you have privileges to add constraints to them, just like I do for models and snapshots.
