### ISSUE TITLE
Doesn't work when name != alias

### ISSUE THREAD

**Issue by akdor1154** [Snowflake-Labs/dbt_constraints#4]
Hey
Thanks for publishing this!
I noticed that it doesn't seem to work when a model is published with an alias.
I think that 
`create_constraints.sql:203`
```jinja
            {%- set table_relation = adapter.get_relation(
                database=table_models[0].database,
                schema=table_models[0].schema,
                identifier=table_models[0].name) -%}
```
should become
```jinja
...
                identifier=table_models[0].alias) -%}
```
,
and similar changes on :243 and :248 in the same file.

I wonder if there could be a better way of getting a relation from a node/model than `adaptor.get_relation`? I couldn't find one.. but surely it must exist...

**Comment by danflippo** [comment]
Thanks for letting me know about the bug. In addition to your code I added a line when I am looping through sources because they don't support alias (at least not at present). 
```yml
{%- do node.update({'alias': node.alias or node.name }) -%}
```

I am going to merge this branch with main and publish a new version shortly. In the meantime, you can pull the latest changes from Github with the following in your packages.yml:
```yml
  - git: "https://github.com/Snowflake-Labs/dbt_constraints.git"
    revision: main
```
