### ISSUE TITLE
Decouple constraints from tests

### ISSUE THREAD

**Issue by kamilamarcinekpgs** [Snowflake-Labs/dbt_constraints#44]
Because NOT NULL is enforced by Snowflake, I can rely on it. So if I have this constraint, running the test is pointless. 

On the other hand in some cases we might want to NOT set any constraint, but still run the test, just to asses quality of the upstream data, but not interrupt our transformations in case of nulls.

To sum up, I would like to be able to choose any of combinations:
- set constraint, don't run test
- set constraint and run test
- don't set constraint, run test

**Comment by sfc-gh-dflippo** [comment]
I don't control whether or when a test is executed - that is entirely controlled by dbt Core. 

The package does control whether a constraint is created but setting a column as not null takes almost zero time and no consumption on Snowflake because cloud services already knows in its statistics if any existing micro-partitions have a null in a column. The package does provide a variable that you can set to selectively disable which type of constraints to create. You could set that variable dynamically using an environment variable to selectively disable creating the not_null constraints.
