### ISSUE TITLE
Foreign key constraints tested more than once

### ISSUE THREAD

**Issue by lucianmoldovanu** [Snowflake-Labs/dbt_constraints#62]
**Foreign key constraints** are inherently double-ended: they have the source model (originating-end) where the FK is declared, and there is the target model (receiving-end) to the PK of which the relationship refers.

When defining a test constraint using `dbt_constraints.foreign_key` package between models `A (fk) -> (pk) B`, running all tests on the receiving-end models (i.e. `dbt test -m B`) triggers the testing of the foreign key constraint as well.

For an orchestration scenario that I am prototyping, I would however prefer to **avoid** running the receiving-end FK test. Thus when testing model A I want the FK test to be evaluated, yet when testing model B I **do not** want the FK test to be evaluated again.

Is this feature covered? If so, how?

_I have the workaround to parse the DBT manifest and explicitly define which tests to run (on model B, in the example above, after I exclude the receiving-ends of FK tests) yet I would be interested in a more elegant solution._

**Comment by sfc-gh-dflippo** [comment]
I want to amend what I said because I double-checked and there now is an out of the box configuration you can use to disable test executions selectively:
[resource-config: enabled](https://docs.getdbt.com/reference/resource-configs/enabled)
[resource-paths](https://docs.getdbt.com/reference/resource-configs/resource-path)
example dbt_project.yml
```yaml
tests:
  my_package_name:
    +enabled: true | false
```
I believe you should use this feature to control which tests are executed. By using environment variables and a selective path, I believe you should be able to control the execution of tests for the upstream package or just a part of it. If a test doesn't run, dbt Constraints won't create any constraints.

I am also now planning to add a similar `dbt_constraints_enabled` configuration property that would allow users to run the tests but skip the constraints but I don't think that would apply to your use case since you don't want the tests to run.
