### ISSUE TITLE
can we set a particular test severity to warn at project level ?

### ISSUE THREAD

**Issue by choudrybabu** [Snowflake-Labs/dbt_constraints#78]
we would like to set Foreign_key test to warn at a project level , is this possible ?
i have tried adding few configurations in project yml file but no luck 

tests:
  dbt_constraints:
      +severity: warn
      tests:
        foreign_key:
          +severity: warn

models:
  dbt_constraints:
      +severity: warn
      tests:
        foreign_key:
          +severity: warn

**Comment by sfc-gh-dflippo** [comment]
Your question has to do with dbt Core functionality, not dbt Constraints. I believe you can set severity to a macro or jinja expression, instead of a static value so you might want to try that. The tests in dbt Constraints behave just like any other dbt tests, including the out of the box tests. Whether they warn or fail a project is not part of the extension, sorry.
